Repository e2b-dev/E2B, pull requests merged in 2024-12, with the labels that each got.

#499 Redirect to localhost instead of e2b.dev after sign in with oauth in dev environment
  apps/web/src/components/AuthForm.tsx
Labels: dashboard

#505 Make stdout and stderr handle decode errors gracefully
  packages/python-sdk/e2b/sandbox_async/commands/command_handle.py
  packages/python-sdk/e2b/sandbox_sync/commands/command_handle.py
  packages/python-sdk/tests/async/sandbox_async/commands/test_run.py
  packages/python-sdk/tests/sync/sandbox_sync/commands/test_run.py
Labels: bug

#522 Add search capabilities to documentation
  apps/web/src/components/Header.tsx
  apps/web/src/components/Layout.tsx
  apps/web/src/components/MobileBurgerMenu.tsx
  apps/web/src/components/Search.tsx
  apps/web/src/mdx/search.mjs
  apps/web/types.d.ts
Labels: docs
