Repository e2b-dev/E2B, pull requests merged in 2025-07, with the labels that each got.

#806 Fixes parsing http errors in connect client
  .changeset/mighty-dragons-shake.md
  packages/python-sdk/e2b/envd/rpc.py
  packages/python-sdk/e2b_connect/client.py
Labels: bug

#804 Add sandbox metadata docs and update env var tests
  apps/web/src/app/(docs)/docs/sandbox/environment-variables/page.mdx
  packages/js-sdk/tests/integration/randomness.test.ts
  packages/js-sdk/tests/sandbox/commands/envVars.test.ts
  packages/python-sdk/tests/async/sandbox_async/commands/test_env_vars.py
  packages/python-sdk/tests/sync/sandbox_sync/commands/test_env_vars.py
Labels: docs

#814 Print all logs also on build success
  .changeset/shy-knives-shake.md
  packages/cli/src/commands/template/build.ts
Labels: Improvement

#820 Client ID part removal from SDKs
  .changeset/green-roses-know.md
  packages/cli/src/commands/sandbox/connect.ts
  packages/cli/src/commands/sandbox/list.ts
  packages/js-sdk/src/sandbox/sandboxApi.ts
  packages/python-sdk/e2b/sandbox/sandbox_api.py
  packages/python-sdk/e2b/sandbox_async/sandbox_api.py
  packages/python-sdk/e2b/sandbox_sync/sandbox_api.py
Labels: Improvement

#821 Support sandbox domain in sdk and cli
  .changeset/purple-kangaroos-tease.md
  packages/js-sdk/src/api/schema.gen.ts
  packages/js-sdk/src/sandbox/index.ts
  packages/js-sdk/src/sandbox/sandboxApi.ts
  packages/python-sdk/e2b/api/__init__.py
  packages/python-sdk/e2b/api/client/api/sandboxes/get_sandboxes_metrics.py
  packages/python-sdk/e2b/api/client/api/sandboxes/get_sandboxes_sandbox_id_metrics.py
  packages/python-sdk/e2b/api/client/models/__init__.py
  packages/python-sdk/e2b/api/client/models/created_access_token.py
  packages/python-sdk/e2b/api/client/models/created_team_api_key.py
  packages/python-sdk/e2b/api/client/models/identifier_masking_details.py
  packages/python-sdk/e2b/api/client/models/node.py
  packages/python-sdk/e2b/api/client/models/node_detail.py
  packages/python-sdk/e2b/api/client/models/running_sandbox_with_metrics.py
  packages/python-sdk/e2b/api/client/models/sandbox.py
  packages/python-sdk/e2b/api/client/models/sandbox_detail.py
  packages/python-sdk/e2b/api/client/models/sandbox_metric.py
  packages/python-sdk/e2b/api/client/models/sandboxes_with_metrics.py
  packages/python-sdk/e2b/api/client/models/team_api_key.py
  packages/python-sdk/e2b/api/client/models/template_build.py
  packages/python-sdk/e2b/api/client/models/template_build_request.py
  packages/python-sdk/e2b/sandbox/main.py
  packages/python-sdk/e2b/sandbox/sandbox_api.py
  packages/python-sdk/e2b/sandbox/signature.py
  packages/python-sdk/e2b/sandbox_async/main.py
  packages/python-sdk/e2b/sandbox_async/sandbox_api.py
  packages/python-sdk/e2b/sandbox_sync/filesystem/filesystem.py
  packages/python-sdk/e2b/sandbox_sync/main.py
  packages/python-sdk/e2b/sandbox_sync/sandbox_api.py
  packages/python-sdk/e2b_connect/client.py
  packages/python-sdk/tests/async/sandbox_async/commands/test_cmd_list.py
  packages/python-sdk/tests/async/sandbox_async/files/test_exists.py
  packages/python-sdk/tests/async/sandbox_async/files/test_remove.py
  packages/python-sdk/tests/async/sandbox_async/files/test_secured.py
  packages/python-sdk/tests/async/sandbox_async/test_connect.py
  packages/python-sdk/tests/async/sandbox_async/test_secure.py
  packages/python-sdk/tests/sync/sandbox_sync/files/test_secured.py
  packages/python-sdk/tests/sync/sandbox_sync/test_secure.py
  spec/openapi.yml
Labels: feature

#819 Add image URI mask option for template build to allow custom image repository
  .changeset/clever-pets-complain.md
  packages/cli/src/commands/template/build.ts
Labels: feature

#825 Add note about Debian based images limitation
  apps/web/src/app/(docs)/docs/sandbox-template/page.mdx
Labels: docs

#830 Update `User-Agent` header in SDKs based on the SDK version
  .changeset/plenty-foxes-press.md
  packages/js-sdk/src/api/metadata.ts
  packages/js-sdk/src/connectionConfig.ts
  packages/js-sdk/src/sandbox/index.ts
  packages/python-sdk/e2b/api/metadata.py
  packages/python-sdk/e2b/connection_config.py
  packages/python-sdk/e2b_connect/client.py
Labels: bug

#832 Update documentation title for file and directory metadata
  apps/web/src/components/Navigation/routes.tsx
Labels: docs

#838 Remove new tags from Metrics and Persistence
  apps/web/src/components/Navigation/routes.tsx
Labels: docs

#839 Sort SDK version for dropdown using semver package
  apps/web/package.json
  apps/web/src/components/Navigation/index.tsx
  apps/web/src/components/SdkVersionSelect.tsx
  pnpm-lock.yaml
Labels: bug, docs
