Repository e2b-dev/E2B, pull requests merged in 2025-09, with the labels that each got.

#893 Add ready command for JS and Python
  .changeset/dirty-chicken-allow.md
  packages/js-sdk/src/template/index.ts
  packages/js-sdk/src/template/types.ts
  packages/python-sdk/e2b/template/main.py
Labels: feature

#895 Vendor strip-ansi npm module to avoid ESM-related issues
  .changeset/hungry-cups-warn.md
  packages/js-sdk/package.json
  packages/js-sdk/src/template/buildApi.ts
  packages/js-sdk/src/template/types.ts
  packages/js-sdk/src/utils.ts
  pnpm-lock.yaml
Labels: javascript

#900 Add title for Sandbox persistence in docs
  apps/web/src/app/(docs)/docs/sandbox/persistence/page.mdx
Labels: bug

#897 Add custom registries support for pulling base images
  .changeset/tough-squids-wash.md
  .vscode/settings.json
  packages/js-sdk/src/template/index.ts
  packages/js-sdk/src/template/types.ts
  packages/js-sdk/src/template/utils.ts
  packages/python-sdk/e2b/template/main.py
  packages/python-sdk/e2b/template/types.py
  packages/python-sdk/e2b/template/utils.py
  packages/python-sdk/e2b/template_async/build_api.py
  packages/python-sdk/e2b/template_sync/build_api.py
Labels: feature

#920 Improve envd version handling
  packages/js-sdk/src/envd/api.ts
  packages/js-sdk/src/envd/versions.ts
  packages/js-sdk/src/sandbox/commands/index.ts
  packages/js-sdk/src/sandbox/index.ts
  packages/python-sdk/e2b/envd/versions.py
  packages/python-sdk/e2b/sandbox/main.py
  packages/python-sdk/e2b/sandbox_async/commands/command.py
  packages/python-sdk/e2b/sandbox_async/filesystem/filesystem.py
  packages/python-sdk/e2b/sandbox_async/main.py
  packages/python-sdk/e2b/sandbox_sync/commands/command.py
  packages/python-sdk/e2b/sandbox_sync/filesystem/filesystem.py
  packages/python-sdk/e2b/sandbox_sync/main.py
Labels: Improvement

#922 Scope template build for typescript and python
  packages/cli/src/templates/python-build-sync.hbs
  packages/cli/src/templates/typescript-build.hbs
  packages/cli/tests/commands/template/fixtures/complex-python/e2b.toml
  packages/cli/tests/commands/template/fixtures/complex-python/expected/python-async/build_dev.py
  packages/cli/tests/commands/template/fixtures/complex-python/expected/python-async/build_prod.py
  packages/cli/tests/commands/template/fixtures/complex-python/expected/python-sync/build_dev.py
  packages/cli/tests/commands/template/fixtures/complex-python/expected/python-sync/build_prod.py
  packages/cli/tests/commands/template/fixtures/complex-python/expected/typescript/build.dev.ts
  packages/cli/tests/commands/template/fixtures/complex-python/expected/typescript/build.prod.ts
  packages/cli/tests/commands/template/fixtures/copy-variations/expected/python-sync/build_dev.py
  packages/cli/tests/commands/template/fixtures/copy-variations/expected/python-sync/build_prod.py
  packages/cli/tests/commands/template/fixtures/copy-variations/expected/typescript/build.dev.ts
  packages/cli/tests/commands/template/fixtures/copy-variations/expected/typescript/build.prod.ts
  packages/cli/tests/commands/template/fixtures/custom-commands/expected/python-sync/build_dev.py
  packages/cli/tests/commands/template/fixtures/custom-commands/expected/python-sync/build_prod.py
  packages/cli/tests/commands/template/fixtures/custom-commands/expected/typescript/build.dev.ts
  packages/cli/tests/commands/template/fixtures/custom-commands/expected/typescript/build.prod.ts
  packages/cli/tests/commands/template/fixtures/minimal-dockerfile/expected/python-sync/build_dev.py
  packages/cli/tests/commands/template/fixtures/minimal-dockerfile/expected/python-sync/build_prod.py
  packages/cli/tests/commands/template/fixtures/minimal-dockerfile/expected/typescript/build.dev.ts
  packages/cli/tests/commands/template/fixtures/minimal-dockerfile/expected/typescript/build.prod.ts
  packages/cli/tests/commands/template/fixtures/multi-stage/expected/python-sync/build_dev.py
  packages/cli/tests/commands/template/fixtures/multi-stage/expected/python-sync/build_prod.py
  packages/cli/tests/commands/template/fixtures/multi-stage/expected/typescript/build.dev.ts
  packages/cli/tests/commands/template/fixtures/multi-stage/expected/typescript/build.prod.ts
  packages/cli/tests/commands/template/fixtures/multiple-env/expected/python-sync/build_dev.py
  packages/cli/tests/commands/template/fixtures/multiple-env/expected/python-sync/build_prod.py
  packages/cli/tests/commands/template/fixtures/multiple-env/expected/typescript/build.dev.ts
  packages/cli/tests/commands/template/fixtures/multiple-env/expected/typescript/build.prod.ts
  packages/cli/tests/commands/template/fixtures/start-cmd/expected/python-sync/build_dev.py
  packages/cli/tests/commands/template/fixtures/start-cmd/expected/python-sync/build_prod.py
  packages/cli/tests/commands/template/fixtures/start-cmd/expected/typescript/build.dev.ts
  packages/cli/tests/commands/template/fixtures/start-cmd/expected/typescript/build.prod.ts
Labels: bug, Improvement

#919 Set stdin to `/dev/null` by default
  .changeset/quick-fireants-complain.md
  packages/js-sdk/src/envd/process/process_pb.ts
  packages/js-sdk/src/envd/versions.ts
  packages/js-sdk/src/sandbox/commands/index.ts
  packages/js-sdk/tests/sandbox/commands/sendStdin.test.ts
  packages/python-sdk/e2b/envd/process/process_pb2.py
  packages/python-sdk/e2b/envd/process/process_pb2.pyi
  packages/python-sdk/e2b/envd/versions.py
  packages/python-sdk/e2b/sandbox_async/commands/command.py
  packages/python-sdk/e2b/sandbox_sync/commands/command.py
  packages/python-sdk/tests/async/sandbox_async/commands/test_send_stdin.py
  packages/python-sdk/tests/sync/sandbox_sync/commands/test_send_stdin.py
  spec/envd/process/process.proto
Labels: feature

#924 fix: add queue for terminal input
  .changeset/grumpy-moons-melt.md
  packages/cli/src/terminal.ts
Labels: bug
