Repository e2b-dev/E2B, pull requests merged in 2025-01, with the labels that each got.

#533 Show badge for legacy documentation search results
  apps/web/src/components/Search.tsx
  apps/web/src/mdx/search.mjs
  apps/web/types.d.ts
Labels: Improvement, dashboard

#534 Capture documentation search analytics & improve legacy docs handling
  apps/web/package.json
  apps/web/src/components/LegacyBanner.tsx
  apps/web/src/components/Search.tsx
  apps/web/src/components/mdx.tsx
  pnpm-lock.yaml
Labels: Improvement, dashboard

#535 Fix duplicate search analytics event captures
  apps/web/src/components/LegacyBanner.tsx
  apps/web/src/components/Search.tsx
Labels: bug, Improvement, dashboard

#542 Generate only relevant api routes for the client in SDKs
  packages/js-sdk/package.json
  packages/js-sdk/src/api/schema.gen.ts
  packages/python-sdk/Makefile
  packages/python-sdk/e2b/api/client/api/auth/__init__.py
  packages/python-sdk/e2b/api/client/api/auth/get_teams.py
  packages/python-sdk/e2b/api/client/api/default/__init__.py
  packages/python-sdk/e2b/api/client/api/default/get_health.py
  packages/python-sdk/e2b/api/client/api/sandboxes/delete_sandboxes_sandbox_id.py
  packages/python-sdk/e2b/api/client/api/sandboxes/get_sandboxes.py
  packages/python-sdk/e2b/api/client/api/sandboxes/get_sandboxes_sandbox_id_logs.py
  packages/python-sdk/e2b/api/client/api/sandboxes/post_sandboxes.py
  packages/python-sdk/e2b/api/client/api/templates/__init__.py
  packages/python-sdk/e2b/api/client/api/templates/delete_templates_template_id.py
  packages/python-sdk/e2b/api/client/api/templates/get_templates.py
  packages/python-sdk/e2b/api/client/api/templates/get_templates_template_id_builds_build_id_status.py
  packages/python-sdk/e2b/api/client/api/templates/post_templates.py
  packages/python-sdk/e2b/api/client/api/templates/post_templates_template_id.py
  packages/python-sdk/e2b/api/client/api/templates/post_templates_template_id_builds_build_id.py
  packages/python-sdk/e2b/api/client/models/__init__.py
  packages/python-sdk/e2b/api/client/models/new_sandbox.py
  packages/python-sdk/e2b/api/client/models/running_sandbox.py
  packages/python-sdk/e2b/api/client/models/sandbox.py
  packages/python-sdk/e2b/api/client/models/sandbox_log.py
  packages/python-sdk/e2b/api/client/models/team.py
  packages/python-sdk/e2b/api/client/models/template.py
  packages/python-sdk/e2b/api/client/models/template_build.py
  packages/python-sdk/e2b/api/client/models/template_build_request.py
  spec/openapi.yml
  spec/remove_extra_tags.py
Labels: Improvement

#519 Boilerplate for integration tests (within js-sdk)
  packages/js-sdk/package.json
  packages/js-sdk/tests/integration/stress.test.ts
  packages/js-sdk/tests/integration/template/README.md
  packages/js-sdk/tests/integration/template/e2b.Dockerfile
  packages/js-sdk/tests/integration/template/e2b.toml
  packages/js-sdk/tests/setup.ts
  packages/js-sdk/vitest.workspace.mts
Labels: Improvement

#548 Add envd version to SDKs
  packages/js-sdk/src/envd/api.ts
  packages/js-sdk/src/sandbox/index.ts
  packages/js-sdk/src/sandbox/sandboxApi.ts
  packages/js-sdk/tests/sandbox/create.test.ts
  packages/python-sdk/e2b/api/__init__.py
  packages/python-sdk/e2b/sandbox_async/main.py
  packages/python-sdk/e2b/sandbox_async/sandbox_api.py
  packages/python-sdk/e2b/sandbox_sync/main.py
  packages/python-sdk/e2b/sandbox_sync/sandbox_api.py
  packages/python-sdk/tests/async/sandbox_async/test_create.py
  packages/python-sdk/tests/sync/sandbox_sync/test_create.py
Labels: Improvement

#543 Add metrics methods to SDKs
  Makefile
  apps/web/src/app/(docs)/docs/sandbox/list/page.mdx
  apps/web/src/app/(docs)/docs/sandbox/metadata/page.mdx
  apps/web/src/components/Pricing/SwitchToProButton.tsx
  apps/web/src/utils/useUser.tsx
  packages/cli/src/commands/sandbox/index.ts
  packages/cli/src/commands/sandbox/logs.ts
  packages/cli/src/commands/sandbox/metrics.ts
  packages/js-sdk/package.json
  packages/js-sdk/src/api/schema.gen.ts
  packages/js-sdk/src/envd/api.ts
  packages/js-sdk/src/sandbox/index.ts
  packages/js-sdk/src/sandbox/sandboxApi.ts
  packages/js-sdk/tests/integration/stress.test.ts
  packages/js-sdk/tests/integration/template/README.md
  packages/js-sdk/tests/integration/template/e2b.Dockerfile
  packages/js-sdk/tests/integration/template/e2b.toml
  packages/js-sdk/tests/sandbox/commands/envVars.test.ts
  packages/js-sdk/tests/sandbox/create.test.ts
  packages/js-sdk/tests/sandbox/metrics.test.ts
  packages/js-sdk/tests/setup.ts
  packages/js-sdk/vitest.workspace.mts
  packages/python-sdk/e2b/api/__init__.py
  packages/python-sdk/e2b/api/client/api/sandboxes/get_sandboxes_sandbox_id_metrics.py
  packages/python-sdk/e2b/api/client/models/__init__.py
  packages/python-sdk/e2b/api/client/models/sandbox_metric.py
  packages/python-sdk/e2b/sandbox/main.py
  packages/python-sdk/e2b/sandbox/sandbox_api.py
  packages/python-sdk/e2b/sandbox_async/commands/command_handle.py
  packages/python-sdk/e2b/sandbox_async/main.py
  packages/python-sdk/e2b/sandbox_async/sandbox_api.py
  packages/python-sdk/e2b/sandbox_sync/commands/command_handle.py
  packages/python-sdk/e2b/sandbox_sync/main.py
  packages/python-sdk/e2b/sandbox_sync/sandbox_api.py
  packages/python-sdk/tests/async/sandbox_async/test_create.py
  packages/python-sdk/tests/async/sandbox_async/test_metrics.py
  packages/python-sdk/tests/sync/sandbox_sync/commands/test_run.py
  packages/python-sdk/tests/sync/sandbox_sync/test_create.py
  packages/python-sdk/tests/sync/sandbox_sync/test_metrics.py
  spec/openapi.yml
Labels: feature

#551 Implement budget alerts & limit
  apps/web/src/app/(dashboard)/dashboard/page.tsx
  apps/web/src/components/Dashboard/AccountSelector.tsx
  apps/web/src/components/Dashboard/BillingAlerts.tsx
  apps/web/src/components/Dashboard/Usage.tsx
  apps/web/src/components/ui/alert-dialog.tsx
  apps/web/src/components/ui/skeleton.tsx
  apps/web/src/utils/useUser.tsx
  package.json
Labels: feature, dashboard

#552 Add sandbox metrics docs page
  apps/web/src/app/(docs)/docs/sandbox/metrics/page.mdx
  apps/web/src/components/Navigation/routes.tsx
Labels: docs

#488 Add recursive directory watch
  .changeset/good-peas-rule.md
  apps/web/src/app/(docs)/docs/filesystem/watch/page.mdx
  packages/js-sdk/src/envd/filesystem/filesystem_pb.ts
  packages/js-sdk/src/envd/versions.ts
  packages/js-sdk/src/sandbox/filesystem/index.ts
  packages/js-sdk/tests/sandbox/files/watch.test.ts
  packages/python-sdk/e2b/api/client/api/sandboxes/delete_sandboxes_sandbox_id.py
  packages/python-sdk/e2b/api/client/api/sandboxes/post_sandboxes_sandbox_id_pause.py
  packages/python-sdk/e2b/api/client/api/sandboxes/post_sandboxes_sandbox_id_refreshes.py
  packages/python-sdk/e2b/api/client/api/sandboxes/post_sandboxes_sandbox_id_timeout.py
  packages/python-sdk/e2b/api/client/client.py
  packages/python-sdk/e2b/api/client/models/__init__.py
  packages/python-sdk/e2b/envd/filesystem/filesystem_pb2.py
  packages/python-sdk/e2b/envd/filesystem/filesystem_pb2.pyi
  packages/python-sdk/e2b/envd/process/process_pb2.py
  packages/python-sdk/e2b/envd/versions.py
  packages/python-sdk/e2b/sandbox/main.py
  packages/python-sdk/e2b/sandbox_async/filesystem/filesystem.py
  packages/python-sdk/e2b/sandbox_async/main.py
  packages/python-sdk/e2b/sandbox_async/sandbox_api.py
  packages/python-sdk/e2b/sandbox_sync/filesystem/filesystem.py
  packages/python-sdk/e2b/sandbox_sync/main.py
  packages/python-sdk/e2b/sandbox_sync/sandbox_api.py
  packages/python-sdk/tests/async/sandbox_async/files/test_watch.py
  packages/python-sdk/tests/sync/sandbox_sync/files/test_watch.py
  spec/envd/filesystem/filesystem.proto
Labels: feature, sdk
