Repository e2b-dev/E2B, pull requests merged in 2025-05, with the labels that each got.

#710 Update connect bucket docs page
  apps/web/src/app/(docs)/docs/legacy/guide/connect-bucket/page.mdx
  apps/web/src/app/(docs)/docs/sandbox/connect-bucket/page.mdx
  apps/web/src/components/Navigation/routes.tsx
Labels: docs

#714 Remove HubSpot contact creation
  supabase/functions/new_user/index.ts
Labels: feature

#718 Revert "Update metrics docs beta note to be public "
  apps/web/src/app/(docs)/docs/sandbox/metrics/page.mdx
Labels: bug

#704 Unify passing of template used in tests and log background commands output
  packages/js-sdk/tests/api/list.test.ts
  packages/js-sdk/tests/cmdHelper.ts
  packages/js-sdk/tests/runtimes/browser/run.test.tsx
  packages/js-sdk/tests/runtimes/bun/run.test.ts
  packages/js-sdk/tests/runtimes/deno/run.test.ts
  packages/js-sdk/tests/sandbox/closed_port.test.ts
  packages/js-sdk/tests/sandbox/commands/envVars.test.ts
  packages/js-sdk/tests/sandbox/commands/run.test.ts
  packages/js-sdk/tests/sandbox/host.test.ts
  packages/js-sdk/tests/setup.ts
  packages/js-sdk/tests/template.ts
  packages/python-sdk/tests/async/api_async/test_sbx_list.py
  packages/python-sdk/tests/async/sandbox_async/commands/test_env_vars.py
  packages/python-sdk/tests/async/sandbox_async/test_host.py
  packages/python-sdk/tests/async/sandbox_async/test_port_closed.py
  packages/python-sdk/tests/conftest.py
  packages/python-sdk/tests/sync/api_sync/test_sbx_list.py
  packages/python-sdk/tests/sync/sandbox_sync/commands/test_env_vars.py
  packages/python-sdk/tests/sync/sandbox_sync/test_host.py
  packages/python-sdk/tests/sync/sandbox_sync/test_port_closed.py
Labels: Improvement

#712 Fix and update integration test template
  packages/js-sdk/tests/integration/template/e2b.Dockerfile
  packages/js-sdk/tests/integration/template/e2b.toml
Labels: Improvement

#722 Remove closed port tests
  packages/js-sdk/tests/sandbox/closed_port.test.ts
  packages/python-sdk/tests/async/sandbox_async/test_port_closed.py
  packages/python-sdk/tests/sync/sandbox_sync/test_port_closed.py
Labels: Improvement

#720 Update dependencies
  pnpm-lock.yaml
Labels: dependencies

#721 Added homebrew installation instructions to the docs
  apps/web/src/app/(docs)/docs/cli/page.mdx
  apps/web/src/app/(docs)/docs/quickstart/install-custom-packages/page.mdx
  apps/web/src/app/(docs)/docs/sandbox-template/page.mdx
  packages/cli/README.md
Labels: docs

#726 Add hugging face to the quickstart guide
  apps/web/src/app/(docs)/docs/quickstart/connect-llms/page.mdx
Labels: docs

#731 Remove sandbox streams
  apps/web/src/app/stream/sandbox/[sandboxId]/page.tsx
Labels: docs

#734 Fix authErrorBox switch breaking
  .changeset/tasty-lemons-grow.md
  packages/cli/src/api.ts
Labels: bug

#735 Added --no-cache option for building templates without cache
  .changeset/ninety-cobras-tan.md
  packages/cli/src/commands/template/build.ts
Labels: Improvement, cli

#742 Remove: legacy docs from search
  apps/web/src/mdx/search.mjs
Labels: docs

#741 Update template start command limits in docs
  apps/web/src/app/(docs)/docs/sandbox-template/start-cmd/page.mdx
Labels: docs

#744 Fix browser tests domain
  packages/js-sdk/tests/runtimes/browser/run.test.tsx
  packages/js-sdk/vitest.workspace.mts
Labels: bug

#732 Updated SDK beta versions in docs
  apps/web/src/app/(docs)/docs/sandbox/installing-beta-sdks/page.mdx
Labels: docs
