Repository e2b-dev/E2B, pull requests merged in 2025-03, with the labels that each got.

#594 Display correct key name for api key
  .changeset/smooth-foxes-cheat.md
  packages/cli/src/api.ts
Labels: bug, cli

#596 Show resolvable url in error message
  .changeset/sweet-geese-yell.md
  DEV.md
  packages/cli/src/api.ts
Labels: bug

#602 Fix SDK reference generation in js-sdk
  packages/js-sdk/package.json
Labels: bug

#603 Update pnpm lockfile
  pnpm-lock.yaml
Labels: bug

#604 Send releases notification to dedicated channel
  .github/workflows/release.yml
Labels: Improvement

#597 Test sandbox closed port error
  packages/js-sdk/tests/sandbox/closed_port.test.ts
  packages/python-sdk/tests/async/sandbox_async/test_port_closed.py
  packages/python-sdk/tests/sync/sandbox_sync/test_port_closed.py
Labels: sdk, Improvement

#610 Clean unused HTMLs
  index.html
  index2.html
Labels: Improvement

#611 Fix docs quick start issues
  apps/web/src/app/(docs)/docs/quickstart/page.mdx
  apps/web/src/app/(docs)/docs/quickstart/upload-download-files/page.mdx
Labels: bug, Improvement

#612 Fix flaky tests - Increase the timeout for pinging the server
  packages/js-sdk/tests/sandbox/closed_port.test.ts
  packages/js-sdk/tests/sandbox/host.test.ts
  packages/python-sdk/tests/async/sandbox_async/test_host.py
  packages/python-sdk/tests/async/sandbox_async/test_port_closed.py
  packages/python-sdk/tests/sync/sandbox_sync/test_host.py
  packages/python-sdk/tests/sync/sandbox_sync/test_port_closed.py
Labels: bug

#613 Fix comments in tests
  packages/python-sdk/tests/async/sandbox_async/test_port_closed.py
  packages/python-sdk/tests/sync/sandbox_sync/test_port_closed.py
Labels: bug

#451 Add multi-file write support to the js and python sdks
  .changeset/new-berries-heal.md
  apps/web/src/app/(docs)/docs/filesystem/read-write/page.mdx
  apps/web/src/app/(docs)/docs/filesystem/upload/page.mdx
  packages/js-sdk/src/index.ts
  packages/js-sdk/src/sandbox/filesystem/index.ts
  packages/js-sdk/tests/sandbox/files/write.test.ts
  packages/python-sdk/e2b/exceptions.py
  packages/python-sdk/e2b/sandbox/filesystem/filesystem.py
  packages/python-sdk/e2b/sandbox_async/filesystem/filesystem.py
  packages/python-sdk/e2b/sandbox_sync/filesystem/filesystem.py
  packages/python-sdk/tests/async/sandbox_async/files/test_write.py
  packages/python-sdk/tests/sync/sandbox_sync/files/test_watch.py
  packages/python-sdk/tests/sync/sandbox_sync/files/test_write.py
Labels: feature, sdk

#615 Fix release test for multi-file write support
  packages/js-sdk/src/sandbox/filesystem/index.ts
  packages/python-sdk/tests/sync/sandbox_sync/files/test_watch.py
Labels: bug

#621 Fix failing write test
  packages/js-sdk/tests/sandbox/files/write.test.ts
Labels: bug

#623 Add temporary docs redirects
  apps/web/next.config.mjs
Labels: Improvement

#624 Fix code interpreting documentation snippets
  apps/web/src/app/(docs)/docs/code-interpreting/analyze-data-with-ai/page.mdx
  apps/web/src/app/(docs)/docs/code-interpreting/create-charts-visualizations/static-charts/page.mdx
Labels: bug, Improvement

#634 Fix Webflow proxying with www-prefixed hostname and proper request handling
  apps/web/src/app/hostnames.ts
  apps/web/src/middleware.ts
Labels: bug

#635 Change default domain in sdks from `e2b.dev` to `e2b.app`
  .changeset/nervous-waves-relate.md
  packages/js-sdk/src/connectionConfig.ts
  packages/python-sdk/e2b/connection_config.py
Labels: sdk, Improvement

#625 Add getInfo/get_info methods to the SDKs
  .changeset/khaki-shirts-switch.md
  apps/web/src/app/(docs)/docs/sandbox/page.mdx
  packages/js-sdk/src/sandbox/index.ts
  packages/js-sdk/src/sandbox/sandboxApi.ts
  packages/js-sdk/tests/sandbox/timeout.test.ts
  packages/python-sdk/e2b/sandbox/sandbox_api.py
  packages/python-sdk/e2b/sandbox_async/main.py
  packages/python-sdk/e2b/sandbox_async/sandbox_api.py
  packages/python-sdk/e2b/sandbox_sync/main.py
  packages/python-sdk/e2b/sandbox_sync/sandbox_api.py
  packages/python-sdk/tests/async/sandbox_async/test_timeout.py
  packages/python-sdk/tests/sync/sandbox_sync/test_timeout.py
Labels: feature

#630 doc: fix typo of file `apps/web/README.md`
  apps/web/README.md
Labels: Improvement

#633 chore(apps/web): update package.json
  apps/web/package.json
  pnpm-lock.yaml
Labels: Improvement

#638 getInfo: added tests, updated documentation with example return
  apps/web/src/app/(docs)/docs/sandbox/page.mdx
  packages/js-sdk/tests/api/info.test.ts
  packages/python-sdk/tests/async/api_async/test_sbx_info.py
  packages/python-sdk/tests/sync/api_sync/test_sbx_info.py
Labels: Improvement

#639 Cli changeset for version release
  .changeset/olive-geese-look.md
Labels: cli, dependencies

#622 Add table column to show template `updatedAt` field
  apps/web/src/components/Dashboard/Templates.tsx
Labels: Improvement

#641 Script for per-package check if release is needed
  .github/scripts/is_release_for_package.sh
  .github/workflows/release.yml
Labels: Improvement

#647 Update Python beta SDK version
  apps/web/src/app/(docs)/docs/sandbox/persistence/page.mdx
Labels: docs

#648 Update package versions
  apps/web/src/app/(docs)/docs/sandbox/metrics/page.mdx
  apps/web/src/app/(docs)/docs/sandbox/persistence/page.mdx
Labels: docs
