Repository e2b-dev/E2B, pull requests merged in 2025-08, with the labels that each got.

#845 Secured sandbox auto signature
  .changeset/wicked-ghosts-tie.md
  apps/web/src/app/(docs)/docs/filesystem/download/page.mdx
  apps/web/src/app/(docs)/docs/filesystem/upload/page.mdx
  packages/js-sdk/src/sandbox/index.ts
  packages/js-sdk/tests/sandbox/files/signing.test.ts
  packages/js-sdk/tests/sandbox/secure.test.ts
  packages/python-sdk/e2b/sandbox/main.py
  packages/python-sdk/tests/async/sandbox_async/files/test_secured.py
  packages/python-sdk/tests/sync/sandbox_sync/files/test_secured.py
Labels: Improvement

#851 Add RateLimitError to export
  .changeset/moody-actors-raise.md
  packages/js-sdk/src/index.ts
Labels: Improvement

#849 Simplify connection config handling in Python SDK
  .changeset/strange-hornets-judge.md
  packages/python-sdk/e2b/connection_config.py
  packages/python-sdk/e2b/sandbox/main.py
  packages/python-sdk/e2b/sandbox/sandbox_api.py
  packages/python-sdk/e2b/sandbox_async/commands/command.py
  packages/python-sdk/e2b/sandbox_async/commands/pty.py
  packages/python-sdk/e2b/sandbox_async/filesystem/filesystem.py
  packages/python-sdk/e2b/sandbox_async/main.py
  packages/python-sdk/e2b/sandbox_async/sandbox_api.py
  packages/python-sdk/e2b/sandbox_sync/commands/command.py
  packages/python-sdk/e2b/sandbox_sync/commands/pty.py
  packages/python-sdk/e2b/sandbox_sync/filesystem/filesystem.py
  packages/python-sdk/e2b/sandbox_sync/main.py
  packages/python-sdk/e2b/sandbox_sync/sandbox_api.py
  packages/python-sdk/tests/sync/sandbox_sync/files/test_secured.py
Labels: Improvement, python

#874 Update pnpm github action to v4
  .github/workflows/cli_tests.yml
  .github/workflows/generated_files.yml
  .github/workflows/js_sdk_tests.yml
  .github/workflows/lint.yml
  .github/workflows/publish_packages.yml
  .github/workflows/release.yml
  .github/workflows/release_candidates.yml
Labels: dependencies

#870 Add migration guide to docs
  apps/web/src/app/(docs)/docs/migration/v2/page.mdx
  apps/web/src/app/(docs)/docs/sandbox/list/page.mdx
  apps/web/src/app/(docs)/docs/sandbox/persistence/page.mdx
  apps/web/src/app/(docs)/docs/sdk-reference/python-sdk/v2.0.0/sandbox_async/page.mdx
  apps/web/src/app/(docs)/docs/sdk-reference/python-sdk/v2.0.0/sandbox_sync/page.mdx
  apps/web/src/components/Navigation/routes.tsx
  apps/web/src/images/diagram.svg
  packages/python-sdk/e2b/sandbox_sync/paginator.py
Labels: docs
