Repository e2b-dev/E2B, pull requests merged in 2025-02, with the labels that each got.

#569 Add assetPrefix to next config
  apps/web/next.config.mjs
Labels: docs, Improvement

#570 Fix: assetPrefix refers to correct domains for production & preview environments
  apps/web/next.config.mjs
Labels: bug, docs

#573 Remove level field and deduplicate timestamp field
  packages/cli/src/commands/sandbox/metrics.ts
Labels: bug

#574 Fix usage in browser
  .changeset/twelve-planets-attend.md
  packages/js-sdk/src/api/metadata.ts
Labels: bug

#575 Drop support for Python 3.8
  .changeset/strange-stingrays-shout.md
  packages/python-sdk/poetry.lock
  packages/python-sdk/pyproject.toml
Labels: dependencies

#576 E2B-1546: add google tag manager capibilites for /docs
  apps/web/src/app/layout.tsx
Labels: feature

#577 Update package manager to the latest 9.x version (9.15.5)
  package.json
Labels: Improvement, infra

#579 Rewrite /category in middleware
  apps/web/src/app/sitemap.ts
  apps/web/src/middleware.ts
  package.json
Labels: feature, dashboard

#578 Fix CLI build issue
  .changeset/stale-owls-own.md
  packages/cli/src/index.ts
  packages/cli/tsup.config.js
Labels: bug

#590 Improve legacy banner visibility in /docs
  apps/web/src/components/LegacyBanner.tsx
  apps/web/src/components/Navigation/routes.tsx
Labels: Improvement

#595 Change twitter links to the new handle
  apps/web/config.ts
  apps/web/src/app/(docs)/docs/legacy/getting-help/page.mdx
  apps/web/src/components/Footer.tsx
  index.html
  index2.html
Labels: bug
