Repository e2b-dev/E2B, pull requests merged in 2025-06, with the labels that each got.

#754 Chore: pass pathname as prop into navigation group to avoid layout shift on initial render
  apps/web/src/components/Navigation/NavigationSubgroup.tsx
  apps/web/src/components/Navigation/index.tsx
Labels: Improvement

#757 Fix: path validation for metadata tags resolution
  apps/web/src/app/layout.tsx
  apps/web/src/app/sitemap.ts
Labels: bug, Improvement

#761 Added license sources to SDKs
  .changeset/tough-dots-live.md
  packages/cli/LICENSE
  packages/js-sdk/LICENSE
  packages/python-sdk/LICENSE
Labels: Improvement

#763 Remove: api-reference routes and set up SEO redirect
  apps/web/next.config.mjs
  apps/web/src/app/(docs)/docs/api-reference/python-sdk/v1.0.4/exceptions/page.mdx
  apps/web/src/app/(docs)/docs/api-reference/python-sdk/v1.0.4/sandbox_async/page.mdx
  apps/web/src/app/(docs)/docs/api-reference/python-sdk/v1.0.4/sandbox_sync/page.mdx
Labels: docs

#750 Add option for a template ready check
  .changeset/four-numbers-drive.md
  apps/web/src/app/(docs)/docs/legacy/sandbox/custom/page.mdx
  apps/web/src/app/(docs)/docs/legacy/sandbox/templates/overview/page.mdx
  apps/web/src/app/(docs)/docs/sandbox-template/page.mdx
  apps/web/src/app/(docs)/docs/sandbox-template/ready-cmd/page.mdx
  apps/web/src/app/(docs)/docs/sandbox-template/start-cmd/page.mdx
  apps/web/src/components/Navigation/routes.tsx
  packages/cli/README.md
  packages/cli/package.json
  packages/cli/src/commands/template/build.ts
  packages/cli/src/config/index.ts
  packages/cli/src/utils/errors.ts
  packages/js-sdk/package.json
  pnpm-lock.yaml
Labels: feature, cli

#778 Changes timeout exception format
  .changeset/curvy-badgers-compete.md
  packages/python-sdk/e2b/exceptions.py
Labels: Improvement

#788 Update deps
  pnpm-lock.yaml
Labels: dependencies

#794 Redirect /docs/getting-help > /docs/support
  apps/web/next.config.mjs
Labels: docs

#796 watchDir remove redundant "timeout" option in JS SDK
  .changeset/twenty-pears-kick.md
  packages/js-sdk/src/sandbox/filesystem/index.ts
Labels: Improvement

#738 Ignore unknown fields from received messages (protobuf)
  .changeset/late-windows-act.md
  packages/python-sdk/e2b_connect/client.py
Labels: Improvement
