Repository e2b-dev/E2B, pull requests merged in 2025-04, with the labels that each got.

#599 Refactor: Convert legacy application to docs-only mode
  apps/web/next.config.mjs
  apps/web/package.json
  apps/web/src/app/(auth)/auth/layout.tsx
  apps/web/src/app/(auth)/auth/reset-password/page.tsx
  apps/web/src/app/(auth)/auth/sign-in/page.tsx
  apps/web/src/app/(auth)/auth/sign-up/page.tsx
  apps/web/src/app/(auth)/auth/update-password/page.tsx
  apps/web/src/app/(dashboard)/dashboard/layout.tsx
  apps/web/src/app/(dashboard)/dashboard/page.tsx
  apps/web/src/app/(dashboard)/dashboard/utils.ts
  apps/web/src/app/(docs)/docs/api/cli/page.tsx
  apps/web/src/app/(docs)/docs/legacy/api/cli/page.tsx
  apps/web/src/app/(docs)/docs/legacy/getting-started/api-key/APIKey.tsx
  apps/web/src/app/(docs)/docs/legacy/getting-started/api-key/page.mdx
  apps/web/src/app/(docs)/docs/legacy/pricing/page.mdx
  apps/web/src/app/layout.tsx
  apps/web/src/app/providers.tsx
  apps/web/src/app/sitemap.ts
  apps/web/src/components/Auth.tsx
  apps/web/src/components/AuthForm.tsx
  apps/web/src/components/Dashboard/AccountSelector.tsx
  apps/web/src/components/Dashboard/Billing.tsx
  apps/web/src/components/Dashboard/BillingAlerts.tsx
  apps/web/src/components/Dashboard/Chart.tsx
  apps/web/src/components/Dashboard/Developer.tsx
  apps/web/src/components/Dashboard/Keys.tsx
  apps/web/src/components/Dashboard/Personal.tsx
  apps/web/src/components/Dashboard/Sandboxes.tsx
  apps/web/src/components/Dashboard/Team.tsx
  apps/web/src/components/Dashboard/Templates.tsx
  apps/web/src/components/Dashboard/Usage.tsx
  apps/web/src/components/Header.tsx
  apps/web/src/components/Layout.tsx
  apps/web/src/components/ManageBilling.tsx
  apps/web/src/components/Pricing/SwitchToHobbyButton.tsx
  apps/web/src/components/Pricing/SwitchToProButton.tsx
  apps/web/src/components/Pricing/TierActiveTag.tsx
  apps/web/src/components/Search.tsx
  apps/web/src/middleware.ts
  apps/web/src/utils/usePostHog.tsx
  apps/web/src/utils/useUser.tsx
  apps/web/vercel.json
  pnpm-lock.yaml
Labels: dashboard

#653 Update Ubuntu base image to 22.04
  .github/workflows/cli_tests.yml
  .github/workflows/js_sdk_tests.yml
  .github/workflows/publish_packages.yml
  .github/workflows/python_sdk_tests.yml
  .github/workflows/supabase.yml
  .github/workflows/templates.yml
Labels: Improvement

#655 Show SDK ref dir only when it exists
  .github/workflows/publish_packages.yml
Labels: bug

#657 Add development shell to manage dependencies
  DEV.md
  flake.lock
  flake.nix
Labels: feature

#660 Add new_user hubspot contact creation
  supabase/functions/new_user/index.ts
Labels: feature

#663 Forward user metadata is_fragments_user to hubspot
  supabase/functions/new_user/index.ts
Labels: feature

#659 docs: note delayed delivery of file system change events
  apps/web/src/app/(docs)/docs/filesystem/watch/page.mdx
Labels: docs, Improvement

#666 Added security.txt under well-known
  apps/web/public/.well-known/security.txt
Labels: Improvement

#671 (Workers) Patch connect-es fetch transport to always use redirect: follow
  .changeset/lemon-maps-sleep.md
  packages/js-sdk/src/sandbox/index.ts
Labels: Improvement

#668 Fix test for closed ports
  packages/js-sdk/tests/sandbox/closed_port.test.ts
  packages/python-sdk/tests/async/sandbox_async/test_port_closed.py
  packages/python-sdk/tests/sync/sandbox_sync/test_port_closed.py
Labels: bug

#672 (fix) re-release 1.2.3 version
  .changeset/dirty-worms-sin.md
Labels: sdk

#675 Remove order check from SDK.
  packages/js-sdk/tests/api/list.test.ts
Labels: javascript

#682 Clone remote desktop & code-interpreter SDK refs into E2B sdk refs folder during publish
  .github/workflows/publish_packages.yml
Labels: bug, docs

#681 Updated docs on Sandbox.list v2
  apps/web/src/app/(docs)/docs/cli/page.mdx
  apps/web/src/app/(docs)/docs/sandbox/connect/page.mdx
  apps/web/src/app/(docs)/docs/sandbox/installing-beta-sdks/page.mdx
  apps/web/src/app/(docs)/docs/sandbox/list/page.mdx
  apps/web/src/app/(docs)/docs/sandbox/metadata/page.mdx
  apps/web/src/app/(docs)/docs/sandbox/metrics/page.mdx
  apps/web/src/app/(docs)/docs/sandbox/persistence/page.mdx
  apps/web/src/components/Navigation/routes.tsx
Labels: docs

#687 bump beta versions
  .changeset/fifty-points-cross.md
  .changeset/serious-rocks-exist.md
  packages/cli/package.json
  packages/js-sdk/package.json
  packages/python-sdk/pyproject.toml
Labels: js-rc, python-rc, cli-rc

#691 Adde CLI beta list command docs
  apps/web/src/app/(docs)/docs/cli/list-sandboxes/page.mdx
  apps/web/src/components/Navigation/routes.tsx
Labels: docs

#695 Add option for proxying SDK requests to API and sandbox
  .changeset/cuddly-buckets-tie.md
  packages/python-sdk/e2b/__init__.py
  packages/python-sdk/e2b/api/__init__.py
  packages/python-sdk/e2b/connection_config.py
  packages/python-sdk/e2b/sandbox_async/main.py
  packages/python-sdk/e2b/sandbox_async/sandbox_api.py
  packages/python-sdk/e2b/sandbox_sync/main.py
  packages/python-sdk/e2b/sandbox_sync/sandbox_api.py
Labels: feature, sdk

#698 Add API key page to docs
  apps/web/src/app/(docs)/docs/quickstart/api-key/page.mdx
  apps/web/src/components/Navigation/routes.tsx
Labels: docs

#699 Fix codesnippet in docs for API Key
  apps/web/src/app/(docs)/docs/api-key/page.mdx
  apps/web/src/components/Navigation/routes.tsx
Labels: bug

#701 Respect `E2B_DOMAIN` for `e2b auth login` in CLI
  .changeset/spotty-eagles-complain.md
  packages/cli/src/user.ts
Labels: cli

#702 Allow for short sandbox id in `e2b sbx connect`
  .changeset/tidy-meals-develop.md
  packages/cli/src/commands/sandbox/connect.ts
Labels: cli

#540 Test new error handling indicating when the sandbox is not found
  packages/js-sdk/tests/sandbox/commands/sendStdin.test.ts
  packages/js-sdk/tests/sandbox/connect.test.ts
  packages/js-sdk/tests/sandbox/host.test.ts
Labels: Improvement

#706 Security patches
  packages/cli/package.json
  packages/js-sdk/package.json
  packages/python-sdk/poetry.lock
  pnpm-lock.yaml
Labels: dependencies

#705 Adds ability to pause Sandbox using Sandbox.pause() static class method
  packages/js-sdk/src/sandbox/index.ts
  packages/js-sdk/tests/api/snapshot.test.ts
  packages/python-sdk/e2b/sandbox_async/main.py
  packages/python-sdk/e2b/sandbox_sync/main.py
  packages/python-sdk/tests/async/api_async/test_sbx_snapshot.py
  packages/python-sdk/tests/sync/api_sync/test_sbx_snapshot.py
Labels: Improvement, python, javascript

#709 Beta release candidate
  packages/js-sdk/package.json
  packages/python-sdk/pyproject.toml
Labels: js-rc, python-rc
